
package View;

import Model.Cliente;
import java.util.*;
import javax.swing.table.DefaultTableModel;


public class FormModalCliente extends javax.swing.JFrame {
    
    
    private int idSelecionado = -1;
    private String nomeSelecionado = null;
    private CadastroEmprestimo telaCadastroEmprestimo;
    public FormModalCliente(CadastroEmprestimo telaCadastroEmprestimo) {
        super();
        initComponents();
        carregaTabela();
        this.telaCadastroEmprestimo = telaCadastroEmprestimo;
        
    }
   
    public void carregaTabela() {
        
        Cliente objcliente = new Cliente();

        DefaultTableModel modelo = (DefaultTableModel) this.jTableCliente.getModel();
        modelo.setNumRows(0);

        ArrayList<Cliente> minhalista = new ArrayList<>();
        minhalista = objcliente.getMinhaListac();

        for (Cliente a : minhalista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getTelefone(),
                a.getEmail(),
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        btnSelecionarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        b_voltar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 627, 10));

        jTextField1.setBackground(new java.awt.Color(26, 29, 33));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 300, 20));

        btnSelecionarCliente.setBackground(new java.awt.Color(249, 211, 98));
        btnSelecionarCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSelecionarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnSelecionarCliente.setText("Selecionar Cliente");
        btnSelecionarCliente.setBorder(null);
        btnSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 320, 50));

        jTableCliente.setBackground(new java.awt.Color(249, 211, 98));
        jTableCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableCliente.setForeground(new java.awt.Color(0, 0, 0));
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "TELEFONE", "EMAIL"
            }
        ));
        jTableCliente.setSelectionBackground(new java.awt.Color(249, 178, 22));
        jTableCliente.setShowGrid(true);
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 920, 360));

        b_voltar.setBackground(new java.awt.Color(0, 0, 0));
        b_voltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        b_voltar.setForeground(new java.awt.Color(255, 255, 255));
        b_voltar.setText("Voltar");
        b_voltar.setBorder(null);
        b_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(b_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 140, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar cliente JAVA.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarClienteActionPerformed
        if (idSelecionado != -1){
        telaCadastroEmprestimo.PopularCamposTabela(idSelecionado,nomeSelecionado);
        }
        
        
          
    }//GEN-LAST:event_btnSelecionarClienteActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        if (this.jTableCliente.getSelectedRow() != -1) {

            idSelecionado = Integer.parseInt(this.jTableCliente.getValueAt(this.jTableCliente.getSelectedRow(), 0).toString());
            nomeSelecionado = this.jTableCliente.getValueAt(this.jTableCliente.getSelectedRow(), 1).toString();
        }
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void b_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_voltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormModalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormModalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormModalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormModalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                FormModalCliente dialog = new FormModalCliente(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_voltar;
    private javax.swing.JButton btnSelecionarCliente;
    private javax.swing.JLabel fundo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
