package View;

import Model.Emprestimo;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class GerenciaEmprestimo extends javax.swing.JFrame {

    private Emprestimo objemprestimo;

    public GerenciaEmprestimo() {
        initComponents();
        this.objemprestimo = new Emprestimo();
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmprestimo = new javax.swing.JTable();
        g_voltar = new javax.swing.JButton();
        g_cadastrarEmprestimo = new javax.swing.JButton();
        g_apagar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEmprestimo.setBackground(new java.awt.Color(249, 211, 98));
        jTableEmprestimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableEmprestimo.setForeground(new java.awt.Color(0, 0, 0));
        jTableEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID EMPRESTIMO", "ID CLIENTE", "ID FERRAMENTA", "DATA EMPRESTIMO", "DATA DEVOLUCAO"
            }
        ));
        jTableEmprestimo.setGridColor(new java.awt.Color(0, 0, 0));
        jTableEmprestimo.setSelectionBackground(new java.awt.Color(249, 151, 25));
        jTableEmprestimo.setShowGrid(true);
        jTableEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmprestimo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 890, 520));

        g_voltar.setBackground(new java.awt.Color(0, 0, 0));
        g_voltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        g_voltar.setForeground(new java.awt.Color(255, 255, 255));
        g_voltar.setText("Voltar");
        g_voltar.setBorder(null);
        g_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(g_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 190, 40));

        g_cadastrarEmprestimo.setBackground(new java.awt.Color(249, 211, 98));
        g_cadastrarEmprestimo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        g_cadastrarEmprestimo.setForeground(new java.awt.Color(0, 0, 0));
        g_cadastrarEmprestimo.setText("+ Realizar novo empréstimo");
        g_cadastrarEmprestimo.setBorder(null);
        g_cadastrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_cadastrarEmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(g_cadastrarEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 330, 50));

        g_apagar.setBackground(new java.awt.Color(0, 0, 0));
        g_apagar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        g_apagar.setForeground(new java.awt.Color(255, 255, 255));
        g_apagar.setText("Apagar");
        g_apagar.setBorder(null);
        g_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_apagarActionPerformed(evt);
            }
        });
        getContentPane().add(g_apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 700, 190, 40));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Gerenciar Empréstimos JAVA.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void g_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_voltarActionPerformed
        this.setVisible(false);

        TelaPrincipal objeto = new TelaPrincipal();
        objeto.setVisible(true);
    }//GEN-LAST:event_g_voltarActionPerformed

    private void g_cadastrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_cadastrarEmprestimoActionPerformed
        CadastroEmprestimo objeto = new CadastroEmprestimo();

        objeto.setVisible(true);
    }//GEN-LAST:event_g_cadastrarEmprestimoActionPerformed

    private void jTableEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmprestimoMouseClicked
            if (this.jTableEmprestimo.getSelectedRow() != -1) {

            String idCliente = this.jTableEmprestimo.getValueAt(this.jTableEmprestimo.getSelectedRow(), 1).toString();
            String idFerramenta = this.jTableEmprestimo.getValueAt(this.jTableEmprestimo.getSelectedRow(), 2).toString();
            String dataEmprestimo = this.jTableEmprestimo.getValueAt(this.jTableEmprestimo.getSelectedRow(), 3).toString();
            String dataDevolucao = this.jTableEmprestimo.getValueAt(this.jTableEmprestimo.getSelectedRow(), 4).toString();

//            this.g_idCliente.setText(idCliente);
//            this.g_idFerramenta.setText(idFerramenta);
//            this.g_dataEmprestimo.setText(dataEmprestimo);
//            this.g_dataDevolucao.setText(dataDevolucao);
        }
    }//GEN-LAST:event_jTableEmprestimoMouseClicked

    private void g_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_apagarActionPerformed
        try {
            // validando dados da interface gr�fica.
            int id = 0;
            if (this.jTableEmprestimo.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Aluno para APAGAR");
            } else {
                id = Integer.parseInt(this.jTableEmprestimo.getValueAt(this.jTableEmprestimo.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Emprestimo ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Aluno processar
                if (this.objemprestimo.DeleteEmprestimoBD(id)) {

                    // limpa os campos
//                    this.g_idCliente.setText("");
//                    this.g_idFerramenta.setText("");
//                    this.g_dataEmprestimo.setText("");
//                    this.g_dataDevolucao.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Emprestimo Apagada com Sucesso!");

                }

            }

            System.out.println(this.objemprestimo.getMinhaListae().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_g_apagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton g_apagar;
    private javax.swing.JButton g_cadastrarEmprestimo;
    private javax.swing.JButton g_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmprestimo;
    // End of variables declaration//GEN-END:variables

    private void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTableEmprestimo.getModel();
        modelo.setNumRows(0);

        ArrayList<Emprestimo> minhalista = new ArrayList<>();
        minhalista = objemprestimo.getMinhaListae();

        for (Emprestimo a : minhalista) {
            modelo.addRow(new Object[]{
                a.getId_Emprestimo(),
                a.getIdCliente(),
                a.getIdFerramenta(),
                a.getDataEmprestimo(),
                a.getDataDevolucao(),
            });
        }
    }
}
