/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author 1513 FOX
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDoCliente = new javax.swing.JButton();
        caixaDeFerramentas = new javax.swing.JButton();
        Emprestimo = new javax.swing.JButton();
        fundotela = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaDoCliente.setBackground(new java.awt.Color(226, 180, 43));
        areaDoCliente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        areaDoCliente.setText("CLIENTES");
        areaDoCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 180, 43), 1, true));
        areaDoCliente.setPreferredSize(new java.awt.Dimension(163, 30));
        areaDoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaDoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(areaDoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 370, 60));

        caixaDeFerramentas.setBackground(new java.awt.Color(226, 180, 43));
        caixaDeFerramentas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        caixaDeFerramentas.setText("FERRAMENTAS");
        caixaDeFerramentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 180, 43), 1, true));
        caixaDeFerramentas.setPreferredSize(new java.awt.Dimension(163, 30));
        caixaDeFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeFerramentasActionPerformed(evt);
            }
        });
        getContentPane().add(caixaDeFerramentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 370, 60));

        Emprestimo.setBackground(new java.awt.Color(226, 180, 43));
        Emprestimo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Emprestimo.setText("EMPRÉSTIMO");
        Emprestimo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 180, 43), 1, true));
        Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(Emprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 370, 60));

        fundotela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Caixa de Ferramentas Online (1).jpg"))); // NOI18N
        getContentPane().add(fundotela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaDeFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeFerramentasActionPerformed
        GerenciaFerramenta objeto = new GerenciaFerramenta();
        objeto.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_caixaDeFerramentasActionPerformed

    private void areaDoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaDoClienteActionPerformed
        GerenciaCliente objeto = new GerenciaCliente();
        objeto.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_areaDoClienteActionPerformed

    private void EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmprestimoActionPerformed
        GerenciaEmprestimo objeto = new GerenciaEmprestimo();
        objeto.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_EmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Emprestimo;
    private javax.swing.JButton areaDoCliente;
    private javax.swing.JButton caixaDeFerramentas;
    private javax.swing.JLabel fundotela;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
